package channel

import (
	"context"
	"crypto/tls"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptrace"
	"net/url"
	"regexp"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	baseconstant "github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/types"

	"github.com/gin-gonic/gin"
	"github.com/gorilla/websocket"
)

var ErrCapacityFallbackHeaderDeadline = errors.New("capacity fallback response header deadline exceeded")

func clientCancellationError(c *gin.Context) error {
	if c == nil || c.Request == nil {
		return nil
	}
	contextErr := c.Request.Context().Err()
	if errors.Is(contextErr, context.Canceled) {
		return contextErr
	}
	return nil
}

type cancelOnDoneReadCloser struct {
	io.ReadCloser
	cancel context.CancelFunc
	once   sync.Once
}

func (r *cancelOnDoneReadCloser) Read(p []byte) (int, error) {
	n, err := r.ReadCloser.Read(p)
	if err != nil {
		r.once.Do(r.cancel)
	}
	return n, err
}

func (r *cancelOnDoneReadCloser) Close() error {
	r.once.Do(r.cancel)
	return r.ReadCloser.Close()
}

// applyUpstreamContentLength populates req.ContentLength when the upstream
// body is wrapped in a BodyStorage (see relay/common/outbound_body.go).
//
// net/http.NewRequest only auto-detects ContentLength for *bytes.Reader,
// *bytes.Buffer and *strings.Reader. When the body is a type-erased io.Reader
// (which is the case for ReaderOnly(BodyStorage)), the Content-Length header
// would otherwise be omitted, forcing chunked transfer encoding and breaking
// some upstreams that require an explicit Content-Length.
func applyUpstreamContentLength(req *http.Request, info *common.RelayInfo) {
	if info == nil {
		return
	}
	if info.UpstreamRequestBodySize > 0 && req.ContentLength <= 0 {
		req.ContentLength = info.UpstreamRequestBodySize
	}
}

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

// ApplyHeaderOverrideToRequest applies already-resolved channel header
// overrides to custom adaptor requests that cannot use DoApiRequest.
func ApplyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

func getRequestURL(a Adaptor, info *common.RelayInfo) (string, error) {
	if info != nil && strings.TrimSpace(info.ImageRoutingUpstreamPath) != "" {
		path := strings.TrimSpace(info.ImageRoutingUpstreamPath)
		if !strings.HasPrefix(path, "/") || strings.HasPrefix(path, "//") {
			return "", fmt.Errorf("invalid image routing upstream path")
		}
		// Always let the adaptor build its normal URL first. Vertex uses this
		// step to load service-account credentials and to append API-key query
		// auth; replacing the URL before calling it silently breaks both modes.
		defaultURL, err := a.GetRequestURL(info)
		if err != nil {
			return "", err
		}
		if strings.Contains(path, "{model}") {
			path = strings.ReplaceAll(path, "{model}", url.PathEscape(strings.TrimSpace(info.UpstreamModelName)))
		}
		defaultParsed, err := url.Parse(defaultURL)
		if err != nil {
			return "", fmt.Errorf("parse adaptor request url: %w", err)
		}
		var routed *url.URL
		if info.ChannelType == baseconstant.ChannelTypeVertexAi {
			defaultModelIndex := strings.LastIndex(defaultParsed.Path, "/models/")
			routeModelIndex := strings.LastIndex(path, "/models/")
			if defaultModelIndex < 0 || routeModelIndex < 0 {
				return "", fmt.Errorf("vertex image routing path is incompatible with the adaptor request url")
			}
			routedValue := *defaultParsed
			routedValue.Path = defaultParsed.Path[:defaultModelIndex] + path[routeModelIndex:]
			routedValue.RawPath = ""
			routed = &routedValue
		} else if strings.TrimSpace(info.ChannelBaseUrl) == "" || info.ChannelType == baseconstant.ChannelTypeAdvancedCustom {
			if defaultParsed.Scheme == "" || defaultParsed.Host == "" {
				return "", fmt.Errorf("adaptor request url has no absolute provider base")
			}
			routedValue := *defaultParsed
			routedValue.Path = path
			routedValue.RawPath = ""
			routed = &routedValue
		} else {
			routedURL := common.GetFullRequestURL(strings.TrimRight(info.ChannelBaseUrl, "/"), path, info.ChannelType)
			routed, err = url.Parse(routedURL)
			if err != nil {
				return "", fmt.Errorf("parse image routing url: %w", err)
			}
		}
		// The explicit route controls only the path. Keep provider-generated
		// query authentication and any adaptor-specific URL parameters intact.
		routed.RawQuery = defaultParsed.RawQuery
		routed.Fragment = ""
		return routed.String(), nil
	}
	return a.GetRequestURL(info)
}

// ResolveRequestURL applies the shared route snapshot semantics for adaptors
// that must construct and sign their own HTTP requests.
func ResolveRequestURL(a Adaptor, info *common.RelayInfo) (string, error) {
	return getRequestURL(a, info)
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := getRequestURL(a, info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	ApplyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := getRequestURL(a, info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	ApplyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	fullRequestURL, err := getRequestURL(a, info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	for key, value := range headerOverride {
		targetHeader.Set(key, value)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	if upstreamURL, parseErr := url.Parse(fullRequestURL); parseErr == nil {
		recordAttemptUpstreamURL(upstreamURL, info)
	}
	targetConn, _, err := websocket.DefaultDialer.Dial(fullRequestURL, targetHeader)
	if err != nil {
		return nil, fmt.Errorf("dial failed to %s: %w", common.SanitizeURLForLog(fullRequestURL), err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}
func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	recordAttemptUpstreamHost(req, info)
	var client *http.Client
	var err error
	if info.RelayFormat == types.RelayFormatOpenAIImage {
		client, err = service.GetImageHttpClientWithProxy(info.ChannelSetting.Proxy)
	} else {
		client, err = service.GetRelayHttpClientWithProxy(info.ChannelSetting.Proxy, info.IsStream)
	}
	if err != nil {
		return nil, fmt.Errorf("new proxy http client failed: %w", err)
	}
	if info.ChannelType == baseconstant.ChannelTypeAutoDL {
		noRedirectClient := *client
		noRedirectClient.CheckRedirect = func(_ *http.Request, _ []*http.Request) error {
			return http.ErrUseLastResponse
		}
		if transport, ok := client.Transport.(*http.Transport); ok && transport != nil {
			isolatedTransport := transport.Clone()
			isolatedTransport.ForceAttemptHTTP2 = false
			isolatedTransport.DisableKeepAlives = true
			isolatedTransport.TLSNextProto = map[string]func(string, *tls.Conn) http.RoundTripper{}
			if isolatedTransport.TLSClientConfig == nil {
				isolatedTransport.TLSClientConfig = &tls.Config{NextProtos: []string{"http/1.1"}}
			} else {
				isolatedTransport.TLSClientConfig = isolatedTransport.TLSClientConfig.Clone()
				isolatedTransport.TLSClientConfig.NextProtos = []string{"http/1.1"}
			}
			noRedirectClient.Transport = isolatedTransport
		}
		client = &noRedirectClient
	}
	var autoDLTraceStart time.Time
	var autoDLWroteRequestAt atomic.Int64
	var autoDLFirstResponseAt atomic.Int64
	var autoDLWroteRequestFailed atomic.Bool
	if info.ChannelType == baseconstant.ChannelTypeAutoDL {
		autoDLTraceStart = time.Now()
		trace := &httptrace.ClientTrace{
			WroteRequest: func(traceInfo httptrace.WroteRequestInfo) {
				autoDLWroteRequestAt.Store(time.Now().UnixNano())
				autoDLWroteRequestFailed.Store(traceInfo.Err != nil)
			},
			GotFirstResponseByte: func() {
				autoDLFirstResponseAt.Store(time.Now().UnixNano())
			},
		}
		req = req.WithContext(httptrace.WithClientTrace(req.Context(), trace))
	}

	const (
		capacityDeadlinePending int32 = iota
		capacityDeadlineComplete
		capacityDeadlineExpired
	)
	var (
		capacityDeadlineCancel context.CancelFunc
		capacityDeadlineState  atomic.Int32
		capacityDeadlineTimer  *time.Timer
	)
	if info != nil && !info.CapacityFallbackHeaderDeadline.IsZero() {
		remaining := time.Until(info.CapacityFallbackHeaderDeadline)
		if remaining <= 0 {
			if clientErr := clientCancellationError(c); clientErr != nil {
				return nil, types.NewError(clientErr, types.ErrorCodeDoRequestFailed)
			}
			return nil, types.NewError(ErrCapacityFallbackHeaderDeadline, types.ErrorCodeDoRequestFailed)
		}

		deadlineContext, cancel := context.WithCancel(req.Context())
		capacityDeadlineCancel = cancel
		req = req.WithContext(deadlineContext)
		capacityDeadlineTimer = time.AfterFunc(remaining, func() {
			if capacityDeadlineState.CompareAndSwap(capacityDeadlinePending, capacityDeadlineExpired) {
				cancel()
			}
		})
	}

	resp, err := client.Do(req)
	if !autoDLTraceStart.IsZero() {
		wroteRequestMillis := int64(-1)
		firstResponseMillis := int64(-1)
		responseWaitMillis := int64(-1)
		if wroteAt := autoDLWroteRequestAt.Load(); wroteAt > 0 {
			wroteRequestMillis = time.Unix(0, wroteAt).Sub(autoDLTraceStart).Milliseconds()
		}
		if firstResponseAt := autoDLFirstResponseAt.Load(); firstResponseAt > 0 {
			firstResponseMillis = time.Unix(0, firstResponseAt).Sub(autoDLTraceStart).Milliseconds()
			if wroteAt := autoDLWroteRequestAt.Load(); wroteAt > 0 {
				responseWaitMillis = time.Duration(firstResponseAt - wroteAt).Milliseconds()
			}
		}
		logger.LogInfo(c, fmt.Sprintf(
			"AutoDL submit transport timing: wrote_request_ms=%d first_response_ms=%d response_wait_ms=%d client_do_ms=%d write_error=%t request_error=%t",
			wroteRequestMillis,
			firstResponseMillis,
			responseWaitMillis,
			time.Since(autoDLTraceStart).Milliseconds(),
			autoDLWroteRequestFailed.Load(),
			err != nil,
		))
	}
	if capacityDeadlineTimer != nil {
		if capacityDeadlineState.CompareAndSwap(capacityDeadlinePending, capacityDeadlineComplete) {
			capacityDeadlineTimer.Stop()
		}
		if capacityDeadlineState.Load() == capacityDeadlineExpired {
			if resp != nil && resp.Body != nil {
				_ = resp.Body.Close()
			}
			capacityDeadlineCancel()
			if clientErr := clientCancellationError(c); clientErr != nil {
				return nil, types.NewError(clientErr, types.ErrorCodeDoRequestFailed)
			}
			return nil, types.NewError(ErrCapacityFallbackHeaderDeadline, types.ErrorCodeDoRequestFailed)
		}
	}
	if err != nil {
		if capacityDeadlineCancel != nil {
			capacityDeadlineCancel()
		}
		if clientErr := clientCancellationError(c); clientErr != nil {
			return nil, types.NewError(clientErr, types.ErrorCodeDoRequestFailed)
		}
		logger.LogError(c, "do request failed: "+err.Error())
		message := "upstream error: do request failed"
		if info.RelayFormat == types.RelayFormatOpenAIImage {
			var networkError net.Error
			switch {
			case errors.Is(err, context.DeadlineExceeded), errors.As(err, &networkError) && networkError.Timeout():
				message = "image request exceeded the gateway request timeout while waiting for the provider"
			case errors.Is(err, io.EOF), errors.Is(err, io.ErrUnexpectedEOF):
				message = "upstream image connection closed before a response was received"
			}
		}
		return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithHideErrMsg(message))
	}
	if resp == nil {
		if capacityDeadlineCancel != nil {
			capacityDeadlineCancel()
		}
		return nil, errors.New("resp is nil")
	}
	if capacityDeadlineCancel != nil && resp.Body != nil {
		resp.Body = &cancelOnDoneReadCloser{
			ReadCloser: resp.Body,
			cancel:     capacityDeadlineCancel,
		}
	}

	if upID := resp.Header.Get(common2.RequestIdKey); upID != "" {
		c.Set(common2.UpstreamRequestIdKey, upID)
	}

	_ = req.Body.Close()
	_ = c.Request.Body.Close()
	return resp, nil
}

func recordAttemptUpstreamHost(req *http.Request, info *common.RelayInfo) {
	if req == nil {
		return
	}
	recordAttemptUpstreamURL(req.URL, info)
}

func recordAttemptUpstreamURL(upstreamURL *url.URL, info *common.RelayInfo) {
	if upstreamURL == nil || info == nil {
		return
	}
	info.AttemptUpstreamHost = strings.ToLower(strings.TrimSuffix(upstreamURL.Hostname(), "."))
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	applyUpstreamContentLength(req, info)
	req.GetBody = func() (io.ReadCloser, error) {
		return io.NopCloser(requestBody), nil
	}

	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}
